module.exports.cityState = [
  ['New York City', 'New York', 'east'],
  ['Los Angeles', 'California', 'west'], 
  ['Chicago', 'Illinois', 'east'], 
  ['Houston', 'Texas', 'central'], 
  ['Phoenix', 'Arizona', 'south western'], 
  ['Philadelphia', 'Pennsylvania', 'east'], 
  ['San Antonio', 'Texas', 'central'], 
  ['San Diego', 'California', 'west'], 
  ['Baltimore', 'Maryland', 'east'], 
  ['South Lake Tahoe', 'California', 'west'], 
  ['Portland', 'Oregon', 'west'], 
  ['Las Vegas', 'Nevada', 'west'], 
  ['Atlanta', 'Georgia', 'south'], 
  ['Tampa', 'Florida', 'east'], 
  ['Miami', 'Florida', 'east'], 
  ['Detroit', 'Michigan', 'east'], 
  ['Nashville', 'Tennessee', 'south'], 
  ['Seattle', 'Washington', 'west'], 
  ['Charlotte', 'North Carolina', 'south'], 
  ['Boston', 'Massachusetts', 'east'], 
  ['Denver', 'Colorado', 'west'], 
  ['Seattle', 'Washington', 'west'], 
  ['Columbus', 'Ohio', 'east'], 
  ['New Orleans', 'Louisiana', 'south'], 
  ['Charleston', 'South Carolina', 'south'], 
  ['Santa Fe', 'New Mexico', 'west'], 
  ['Savannah', 'Georgia', 'south'], 
  ['Honolulu', 'Hawaii', 'west'], 
  ['Williamsburg', 'Virginia', 'east'], 
  ['San Francisco', 'California', 'west'], 
  ['St. Louis', 'Missouri', 'south'], 
  ['Branson', 'Missouri', 'south'], 
  ['Savannah', 'Georgia', 'south'], 
  ['Indianapolis', 'Indiana', 'central']
];